#!/bin/csh
#PBS -l ncpus=16
#PBS -l walltime=14:00
#PBS -j oe
#PBS -q pri_3

set echo

ja

cd $SCRATCH

cp $HOME/15418/Parallel-LZW/LZW/lzw .

setenv OMP_NUM_THREADS $PBS_NCPUS

		omplace -nt $OMP_NUM_THREADS ./lzw -p 4 -i $HOME/15418/Parallel-LZW/LZW/testData 

ja -chlst
